version: 2.1

commands: 
  checkout_and_install:
    description: "Checkout + Install"
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  store_tar:
    parameters: 
      path:
        type: string
      dest:
        type: string
    steps:
      - run: tar -cf <<parameters.dest>> <<parameters.path>>
      - store_artifacts:
          path: <<parameters.dest>>

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout_and_install
      - run: yarn build --progress false
      - run: tar -cf dist.tar dist/treinamento-cicd
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - store_tar:
          path: dist/treinamento-cicd
          dest: ~/repo/dist.tar

  test-lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout_and_install
      - run: mkdir -p tests-report/tslint
      - run: yarn lint --format junit -o tests-report/tslint/tslint.xml
      - store_test_results:
          path: tests-report
      - store_tar:
          path: tests-report/tslint
          dest: ~/repo/report-tslint.tar

  deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: ls -al ./dist
      - run: echo "Aqui vão os comandos para deploy do seu sistema"

workflows:
  version: 2.1
  build-then-test:
    jobs:
      - test-lint
      - build:
          requires:
            - test-lint
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - dev
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
                - dev
